### ISSUE TITLE
[PD] Course Checklist

### ISSUE THREAD

**Issue by esma-g** [CodeYourFuture/Module-JS1#31]
### Coursework content

Previous CYF trainees built this [course checklist](https://cyf-course-checklist.netlify.app/?authuser=0) to self-assess their understanding.
1. Reflect on your understanding so far
2. Fill in the course checklist for HTML/CSS
3. Take the results to your study group and work on the areas you have identified

You can use this checklist throughout the course.

### Estimated time in hours

0.25

### What is the purpose of this assignment?

This assignment will help you to track your progress during the software development course.

### How to submit

Share the screenshot of the checklist for HTML/CSS on the ticket on your coursework board.

**Comment by kfklein15** [comment]
Duplicate https://github.com/CodeYourFuture/Module-HTML-CSS/issues/35
