### ISSUE TITLE
[PD] Resolving conflicts

### ISSUE THREAD

**Issue by esma-g** [CodeYourFuture/Module-JS1#32]
### Coursework content

Watch this [video](https://www.youtube.com/watch?v=qDfSYz0PX9g&authuser=0) on resolving workplace conflicts.

### Estimated time in hours

0.1

### What is the purpose of this assignment?

This assignment aims to improve your understanding of conflicts in the workplace.

### How to submit

You don't need to submit.

**Comment by kfklein15** [comment]
This will be a prep work for JS2 W2

**Comment by rogerspooner** [comment]
I am working on JS2W2 #7
